<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Fernando H. A. Farache">

<title>Mini Curso - Introdução ao R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-8a894fcc3cb5e37eb5bf30def131be2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="index_files/libs/bootstrap/bootstrap-dark-b15df86742554840d07b04d0f56a07e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="index_files/libs/bootstrap/bootstrap-8a894fcc3cb5e37eb5bf30def131be2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#bem-vindo" id="toc-bem-vindo" class="nav-link active" data-scroll-target="#bem-vindo">Bem-vindo!</a></li>
  <li><a href="#a-interface-do-rstudio" id="toc-a-interface-do-rstudio" class="nav-link" data-scroll-target="#a-interface-do-rstudio">A Interface do RStudio</a></li>
  <li><a href="#criando-um-script" id="toc-criando-um-script" class="nav-link" data-scroll-target="#criando-um-script">Criando um script</a></li>
  <li><a href="#sintaxe-e-operações-aritméticas" id="toc-sintaxe-e-operações-aritméticas" class="nav-link" data-scroll-target="#sintaxe-e-operações-aritméticas">Sintaxe e operações aritméticas</a>
  <ul class="collapse">
  <li><a href="#exemplos-de-operações-aritméticas-no-r" id="toc-exemplos-de-operações-aritméticas-no-r" class="nav-link" data-scroll-target="#exemplos-de-operações-aritméticas-no-r">Exemplos de operações aritméticas no R</a></li>
  </ul></li>
  <li><a href="#atribuição-criando-objetos" id="toc-atribuição-criando-objetos" class="nav-link" data-scroll-target="#atribuição-criando-objetos">Atribuição: criando objetos</a></li>
  <li><a href="#funções" id="toc-funções" class="nav-link" data-scroll-target="#funções">Funções</a>
  <ul class="collapse">
  <li><a href="#ajuda-de-funções" id="toc-ajuda-de-funções" class="nav-link" data-scroll-target="#ajuda-de-funções">Ajuda de funções</a></li>
  <li><a href="#funções-e-argumentos" id="toc-funções-e-argumentos" class="nav-link" data-scroll-target="#funções-e-argumentos">Funções e argumentos</a></li>
  <li><a href="#listar-objetos" id="toc-listar-objetos" class="nav-link" data-scroll-target="#listar-objetos">Listar objetos</a></li>
  <li><a href="#remover-objetos" id="toc-remover-objetos" class="nav-link" data-scroll-target="#remover-objetos">Remover objetos</a></li>
  </ul></li>
  <li><a href="#estruturas-de-dados" id="toc-estruturas-de-dados" class="nav-link" data-scroll-target="#estruturas-de-dados">Estruturas de dados</a>
  <ul class="collapse">
  <li><a href="#vetores" id="toc-vetores" class="nav-link" data-scroll-target="#vetores">Vetores</a></li>
  <li><a href="#conjuntos-de-dados-data-frame" id="toc-conjuntos-de-dados-data-frame" class="nav-link" data-scroll-target="#conjuntos-de-dados-data-frame">Conjuntos de dados (<em>data frame</em>)</a></li>
  </ul></li>
  <li><a href="#organização-de-dados" id="toc-organização-de-dados" class="nav-link" data-scroll-target="#organização-de-dados">Organização de dados</a>
  <ul class="collapse">
  <li><a href="#importando-arquivos-excel-de-maneira-fácil" id="toc-importando-arquivos-excel-de-maneira-fácil" class="nav-link" data-scroll-target="#importando-arquivos-excel-de-maneira-fácil">Importando arquivos Excel de maneira fácil</a></li>
  <li><a href="#copiando-e-colando-os-dados" id="toc-copiando-e-colando-os-dados" class="nav-link" data-scroll-target="#copiando-e-colando-os-dados">Copiando e colando os dados</a></li>
  <li><a href="#visualização-geral-do-conjunto-de-dados" id="toc-visualização-geral-do-conjunto-de-dados" class="nav-link" data-scroll-target="#visualização-geral-do-conjunto-de-dados">Visualização geral do conjunto de dados</a></li>
  </ul></li>
  <li><a href="#análise-exploratória" id="toc-análise-exploratória" class="nav-link" data-scroll-target="#análise-exploratória">Análise exploratória</a>
  <ul class="collapse">
  <li><a href="#estatísticas-descritivas" id="toc-estatísticas-descritivas" class="nav-link" data-scroll-target="#estatísticas-descritivas">Estatísticas descritivas</a></li>
  </ul></li>
  <li><a href="#cálculo-de-várias-estatísticas-descritivas-por-grupo" id="toc-cálculo-de-várias-estatísticas-descritivas-por-grupo" class="nav-link" data-scroll-target="#cálculo-de-várias-estatísticas-descritivas-por-grupo">Cálculo de várias estatísticas descritivas por grupo</a></li>
  <li><a href="#gráficos" id="toc-gráficos" class="nav-link" data-scroll-target="#gráficos">Gráficos</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-dispersão-scatterplot" id="toc-gráfico-de-dispersão-scatterplot" class="nav-link" data-scroll-target="#gráfico-de-dispersão-scatterplot">Gráfico de dispersão (scatterplot)</a></li>
  <li><a href="#boxplots" id="toc-boxplots" class="nav-link" data-scroll-target="#boxplots">Boxplots</a></li>
  </ul></li>
  <li><a href="#inferência-estatística-utilizando-modelos-lineares" id="toc-inferência-estatística-utilizando-modelos-lineares" class="nav-link" data-scroll-target="#inferência-estatística-utilizando-modelos-lineares">Inferência estatística utilizando modelos lineares</a>
  <ul class="collapse">
  <li><a href="#teste-t" id="toc-teste-t" class="nav-link" data-scroll-target="#teste-t">Teste-T</a></li>
  <li><a href="#regressão-linear" id="toc-regressão-linear" class="nav-link" data-scroll-target="#regressão-linear">Regressão linear</a></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">ANOVA</a></li>
  <li><a href="#ancova" id="toc-ancova" class="nav-link" data-scroll-target="#ancova">ANCOVA</a></li>
  <li><a href="#avaliando-os-pressupostos-de-um-modelo" id="toc-avaliando-os-pressupostos-de-um-modelo" class="nav-link" data-scroll-target="#avaliando-os-pressupostos-de-um-modelo">Avaliando os pressupostos de um modelo</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mini Curso - Introdução ao R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Fernando H. A. Farache </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">9 de outubro de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="bem-vindo" class="level2">
<h2 class="anchored" data-anchor-id="bem-vindo">Bem-vindo!</h2>
<p>Faça download dos dados para análises <a href="https://github.com/fhafarache/CursoR/blob/main/dados_R.xlsx"><strong>aqui</strong></a>!</p>
</section>
<section id="a-interface-do-rstudio" class="level2">
<h2 class="anchored" data-anchor-id="a-interface-do-rstudio">A Interface do RStudio</h2>
<p>No RStudio podemos visualizar 4 janelas (<a href="#fig-rstudio_editor" class="quarto-xref">Figura&nbsp;1</a>), sendo elas:</p>
<ul>
<li><strong>Editor</strong>: é onde digitamos os códigos. Nele temos um arquivo de texto que chamamos script. Se ela não aparecer, crie um novo script clicando no botão de atalho do canto superior esquerdo como apresentado no exemplo mais adiante.</li>
<li><strong>Console</strong>: é a linha de comandos do R. Os comandos executados aparecem depois do símbolo “<code>&gt;</code>”, e os resultados também aparecem no console.</li>
<li><strong>Ambiente e história</strong>: onde ficam os objetos criados. “História” apresenta linhas de código recentemente utilizadas.</li>
<li><strong>Output</strong>: Apresenta outras informações, como gráficos gerados, arquivos de ajuda etc.</li>
</ul>
<div id="fig-rstudio_editor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rstudio_editor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/rstudio%20detalhes.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rstudio_editor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Visão geral do RStudio
</figcaption>
</figure>
</div>
</section>
<section id="criando-um-script" class="level2">
<h2 class="anchored" data-anchor-id="criando-um-script">Criando um script</h2>
<p>Uma das melhores formas de registrar as análises realizadas para posteriormente executá-las novamente no R é salvando um script com todas as informações e incluindo os comentários após o “#” de forma a organizar e lembrar o que foi feito. O script pode ser salvo com a extensão .R. Abaixo temos um exemplo de script, utilizando o “#”, e também os símbolos de “<code>=</code>” e “<code>-</code>” de forma a delimitar blocos. Observe que tudo que está após os “#” fica realçado da mesma cor pela marcação de sintaxe (<a href="#fig-rstudio_script" class="quarto-xref">Figura&nbsp;2</a>).</p>
<div id="fig-rstudio_script" class="quarto-float quarto-figure quarto-figure-left anchored" data-fig-align="left">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rstudio_script-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/novo_script.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rstudio_script-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Criando um novo script. O caminho para a criação do script está enfatizado em vermelho
</figcaption>
</figure>
</div>
<p>Abaixo temos um exemplo de texto script:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#==================================================#</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Introdução ao R</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># data: 15 de setembro de 2023</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#==================================================#</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Sintaxe e operações aritméticas ####</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#soma - utilizar o operador aritmético "+"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#subtração - utilizar o operador aritmético "-"</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span> <span class="sc">-</span> <span class="dv">5</span> </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Obs.:</strong> no RStudio, após o título de um tópico iniciado com hashtag, você pode usar 4 hashtags seguidos (<code>####</code>) para indicar um tópico principal; também pode utilizar <code>====</code> para indicar um tópico secundário e <code>----</code> para indicar um tópico terciário.</p>
</section>
<section id="sintaxe-e-operações-aritméticas" class="level2">
<h2 class="anchored" data-anchor-id="sintaxe-e-operações-aritméticas">Sintaxe e operações aritméticas</h2>
<p>O R pode ser utilizado para realizar cálculos simples. Para executar um comando no R, faça alguma das duas ações:</p>
<ul>
<li>Digite <code>1 + 2</code> no <strong>editor</strong> e pressione <code>Ctrl+ENTER.</code> Assim a informação passada no editor será executada no script.</li>
<li>Digite <code>1 + 2</code> diretamente no <strong>console</strong> e pressione <code>ENTER</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>O resultado da digitação aparece como na <a href="#fig-resultado_soma" class="quarto-xref">Figura&nbsp;3</a> .</p>
<div id="fig-resultado_soma" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-resultado_soma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/console.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-resultado_soma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Resultado da soma apresentado no console
</figcaption>
</figure>
</div>
<p>Como resposta, teremos o resultado da operação.</p>
<section id="exemplos-de-operações-aritméticas-no-r" class="level3">
<h3 class="anchored" data-anchor-id="exemplos-de-operações-aritméticas-no-r">Exemplos de operações aritméticas no R</h3>
<p>Você pode realizar as seguintes operações matemáticas e a descrição delas no <strong>editor</strong>. Depois disso, execute-as, deixando a barra de digitação na linha a ser executada e clicando <code>CTRL + ENTER</code>. Você também pode selecionar todo o trecho a ser executado e executar com <code>CTRL + ENTER</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span> <span class="sc">+</span> <span class="dv">5</span> <span class="co">#soma</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span> <span class="sc">-</span> <span class="dv">5</span> <span class="co">#subtração</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span> <span class="sc">*</span> <span class="dv">5</span> <span class="co">#multipicação</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="dv">10</span> <span class="sc">/</span> <span class="dv">5</span> <span class="co">#divisão</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="dv">11</span> <span class="sc">%/%</span> <span class="dv">5</span> <span class="co">#divisão de inteiros</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="dv">11</span> <span class="sc">%%</span> <span class="dv">5</span> <span class="co">#divisão modular</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ao executar o código acima, o resultado será exibido no console <a href="#fig-editor_console" class="quarto-xref">Figura&nbsp;4</a></p>
<div id="fig-editor_console" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-editor_console-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/editor_console.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-editor_console-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Resultado das operações aritméticas digitadas no editor. Após executá-las clicando CTRL + ENTER, os resultados aparecerão no console.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="atribuição-criando-objetos" class="level2">
<h2 class="anchored" data-anchor-id="atribuição-criando-objetos">Atribuição: criando objetos</h2>
<p>Ao executar o comando executado acima, obtemos o resultado da operação. No entanto esse resultado não é salvo em nenhum local. Na linguagem R, para que nosso resultado fique salvo para uma próxima etapa, devemos criar um <strong>objeto</strong>.</p>
<p>O R é uma linguagem orientada a objetos. As planilhas, resultados de análise, funções utilizadas para realizar as análises etc, são salvos como objetos. Para criar objetos, utilizamos o operador de <strong>atribuição (<code>&lt;-</code>)</strong>. Assim, podemos criar um objeto no R que vai salvar o resultado no R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Observe que, diferentemente do passo anterior, não obtivemos um resultado no prompt. Entretanto podemos observar o resultado chamando pelo objeto <em>a</em> que criamos. Para isso, simplesmente escrevemos o nome do objeto (<code>a</code>) no script e clicamos <strong>CTRL+ENTER</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>a</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>Podemos utilizar os símbolos de atribuição como o sinal de menor seguido de hífen, formando uma seta (<code>&lt;-</code>), mas isto em geral também pode ser feito utilizando o sinal de igualdade (<code>=</code>). Após digitar o valor, você poderá utilizar o símbolo de atribuição ao contrário. A função <code>assign()</code> pode ser utilizada para atribuição (obs.: funções são explicadas em um tópico posterior). Todos os comandos abaixo funcionam da mesma forma: atribuem o valor de <code>1 + 2</code> ao objeto <code>a</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span> <span class="ot">-&gt;</span> a</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">assign</span>(<span class="st">"a"</span>, <span class="dv">1</span> <span class="sc">+</span> <span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Nomes de objetos</strong> Podemos colocar o nome que quisermos em um objeto. No exemplo abaixo criamos um objeto de texto (caracteres) <code>Meu.objeto</code>. Para inserir texto, colocamos este entre aspas (<code>""</code>). Observe que ao chamar o objeto, tivemos erro no primeiro caso. isso se deve ao fato de utilizarmos letra maiúscula no nome do objeto. Assim, vemos que a linguagem R e sensível a diferenças entre maiúsculas e minúsculas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Meu.objeto <span class="ot">&lt;-</span> <span class="st">"Aprender R é fácil"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>meu.objeto <span class="co">#retorna uma mensagem de erro, </span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            <span class="co">#pois escrevemos o nome do objeto em minúsculo.</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>Meu.objeto <span class="co">#retorna o resultado esperado</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Observe que todos os objetos criados aparecem na tela superior á esquerda, na aba <strong>Environment</strong>.</p>
<p><strong>Atenção</strong>: Alguns nomes de objeto não são aceitos, por exemplo:</p>
<ul>
<li>O nome de um objeto não pode começar por um número;</li>
<li>O nome de um objeto não pode ser separado por hífen (<code>-</code>);</li>
<li>Não pode haver espaço no nome do objeto</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>meuobjeto <span class="co">#não funciona; nome não pode começar por número</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>meu<span class="sc">-</span>objeto <span class="co">#não funciona</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>meu objeto <span class="co">#erro -não pode haver espaço no nome</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>meu.objeto1 <span class="co">#funciona, nome apresenta número mas só no final.</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Essas limitações podem ser contornadas caso se inclua o nome do objeto entre o sinal <code>``</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">1Meu objeto-</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="st">"Aprender R é fácil"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">1Meu objeto-</span><span class="st">`</span> <span class="co">#funcionou</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="funções" class="level2">
<h2 class="anchored" data-anchor-id="funções">Funções</h2>
<p>Um tipo de objeto que temos no R são as funções. Funções são blocos de código que executam uma tarefa específica e podem ser reutilizados em diferentes partes do seu programa. Elas ajudam a organizar o código, tornando-o mais eficiente e fácil de entender. Funções podem receber entradas (argumentos ou parâmetros) e retornar um valor como resultado. Por exemplo podemos usar a função <code>log</code> para calcular o logaritmo de um determinado valor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="dv">3</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.098612</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(a) <span class="co">#calcula o logaritmo do objeto a</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.098612</code></pre>
</div>
</div>
<p>Assim calculamos o logaritmo de 3. Entretanto, como sabemos qual é a base do logaritmo? Veremos isso a seguir.</p>
<section id="ajuda-de-funções" class="level3">
<h3 class="anchored" data-anchor-id="ajuda-de-funções">Ajuda de funções</h3>
<p>O R apresenta uma documentação abrangente, e para cada função e pacote há uma descrição do seu funcionamento. Essa documentação é importante e permite uma compreensão mais abrangente de como cada função pode ser utilizada. Para entender melhor uma função, podemos realizar pesquisas na ajuda. Isso pode ser realizado de diferentes formas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(log)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>?log</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ao observar a ajuda da função log, no tópico “Usage” observamos que podemos utilizar a função log com a seguinte sintaxe:</p>
<p><code>log(x, base = exp(1))</code></p>
<p>Assim, se quisermos calcular o logaritmo de 10 na base 10, poderíamos fazer isso de qualquer uma das formas a seguir:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="at">x =</span> <span class="dv">100</span>, <span class="at">base =</span> <span class="dv">10</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="funções-e-argumentos" class="level3">
<h3 class="anchored" data-anchor-id="funções-e-argumentos">Funções e argumentos</h3>
<p>Podemos ver que a função log trabalha com 2 <strong>argumentos</strong>, que são o valor (x) e a base do logaritmo. Com isso, podemos ver que as funções apresentam a seguinte sintaxe:</p>
<p><code>função(argumento1 = valor, argumento2 = valor , …)</code></p>
<p>Vocês puderam observar no exemplo que em geral podemos omitir o nome do argumento caso mantenhamos a posição dos argumentos dentro da função.</p>
<p>Você pode realizar diversas operações com objetos, como mostrado abaixo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># se colocados na ordem certa, o nome dos argumentos pode ser omitido</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="dv">100</span>, <span class="dv">10</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="at">base =</span> <span class="dv">10</span>, <span class="dv">100</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Obs.: O objeto <code>a</code> anteriormente tinha o valor 3. Criamos um novo objeto <strong><code>a</code></strong> com valor 10. Desta forma, o valor de <code>a</code> foi alterado.</p>
</section>
<section id="listar-objetos" class="level3">
<h3 class="anchored" data-anchor-id="listar-objetos">Listar objetos</h3>
<p>Você pode listar todos os objetos disponíveis em seu ambiente de trabalho com a função <code>ls()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "a"</code></pre>
</div>
</div>
</section>
<section id="remover-objetos" class="level3">
<h3 class="anchored" data-anchor-id="remover-objetos">Remover objetos</h3>
<p>Um objeto pode ser removido utilizando a função <code>rm()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(Meu.objeto)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>()) <span class="co"># remove todos os objetos criados.</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>() <span class="co">#character(0) - isso quer dizer que não há mais nenhum objeto</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="estruturas-de-dados" class="level2">
<h2 class="anchored" data-anchor-id="estruturas-de-dados">Estruturas de dados</h2>
<p>Estruturas de dados são formas de armazenar e organizar dados para que possam ser utilizados em cálculos. Alguns tipos de estruturas de dados muito utilizados são:</p>
<ul>
<li><strong>Vetores</strong>: uma sequência de valores numéricos ou de caracteres (letras, palavras).</li>
<li><strong>Matrizes</strong>: coleção de vetores em linhas e colunas.</li>
<li><strong>Data frame</strong>: planilha de dados.</li>
<li><strong>Listas</strong>: conjunto de vetores, dataframes ou de matrizes. Versátil.</li>
</ul>
<section id="vetores" class="level3">
<h3 class="anchored" data-anchor-id="vetores">Vetores</h3>
<p>São objetos nos quais podemos guardar vários valores. Criamos vetores utilizando a função de <em>concatenação</em>: <code>c()</code>. Vetores numéricos são as estruturas de dados mais simples do R.</p>
<p>Vamos criar um vetor chamado <code>abundancia</code>, com 10 valores. Após criar o vetor com a função <code>c()</code>, podemos executar o comando <code>abundancia</code>, para ver os 10 valores que digitamos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>abundancia <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">56</span>, <span class="dv">46</span>, <span class="dv">45</span>, <span class="dv">65</span>, <span class="dv">95</span>, <span class="dv">102</span>, <span class="dv">86</span>, <span class="dv">110</span>, <span class="dv">56</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>abundancia</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  30  56  46  45  65  95 102  86 110  56</code></pre>
</div>
</div>
<p>Esses dados correspondem às quantidades de artrópodes coletados em armadilhas de queda (“pitfall”). As cinco primeiras observações foram realizadas em um fragmento florestal e as cinco últimas na matriz do fragmento.<br>
Vamos criar um vetor de caracteres para incluir os nomes correspondentes para cada observação no vetor <code>abundancia</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ambiente <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"fragmento"</span>, <span class="st">"fragmento"</span>, <span class="st">"fragmento"</span>, <span class="st">"fragmento"</span>, <span class="st">"fragmento"</span>, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>              <span class="st">"matriz"</span>, <span class="st">"matriz"</span>, <span class="st">"matriz"</span>, <span class="st">"matriz"</span>, <span class="st">"matriz"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>ambiente</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "fragmento" "fragmento" "fragmento" "fragmento" "fragmento" "matriz"   
 [7] "matriz"    "matriz"    "matriz"    "matriz"   </code></pre>
</div>
</div>
<p><strong>Atenção</strong>: para cada elemento do vetor de texto, deve ser colocado entre aspas (<code>" "</code>).</p>
</section>
<section id="conjuntos-de-dados-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="conjuntos-de-dados-data-frame">Conjuntos de dados (<em>data frame</em>)</h3>
<p>Em geral, quando vamos organizar os dados em uma planilha, utilizamos estruturas muito parecidas com o formato data frame. Neste tipo de objeto temos colunas representando variáveis e linhas representando observações. Vamos utilizar a função <code>data.frame()</code> para criar uma planilha com os dados de artrópodes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>artropodes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ambiente, abundancia)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>artropodes</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ambiente abundancia
1  fragmento         30
2  fragmento         56
3  fragmento         46
4  fragmento         45
5  fragmento         65
6     matriz         95
7     matriz        102
8     matriz         86
9     matriz        110
10    matriz         56</code></pre>
</div>
</div>
</section>
</section>
<section id="organização-de-dados" class="level2">
<h2 class="anchored" data-anchor-id="organização-de-dados">Organização de dados</h2>
<p>A forma de se organizar um conjunto de dados é muito importante, e pode facilitar muito a compreensão da forma como se vai analisar os dados. Existem muitas formas como os dados serão organizados e planilhados, o que pode mudar dependendo da área de pesquisa.</p>
<p>Em um passo inicial, provavelmente os dados serão tabulados em papel ou utilizando uma planilha em um software como Excel, Planilhas do Google ou similar. A organização desses dados muitas vezes depende da área de pesquisa. Entretanto, na hora de se analisar os dados, é necessário aplicar algum sistema de organização que facilite a filtragem, reorganização (<em>data wrangling</em>), preparação de gráficos, estatísticas descritivas e inferência estatística. Podemos chamar esse tipo de conjunto de dados de dados organizados ou <em>tidy data</em> <span class="citation" data-cites="wickham2023">(<a href="#ref-wickham2023" role="doc-biblioref">Wickham, Çetinkaya-Rundel, e Grolemund 2023</a>)</span>.</p>
<p>A organização ideal de um conjunto de dados segue alguns princípios , <a href="#fig-varobval" class="quarto-xref">Figura&nbsp;5</a>:</p>
<ol type="1">
<li><p>Cada variável é representada por uma coluna;</p></li>
<li><p>Cada observação é representada por uma linha e cada linha representa uma observação;</p></li>
<li><p>Cada valor está contido em uma única célula e cada célula contém somente um valor.</p></li>
</ol>
<div id="fig-varobval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-varobval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/VariavelObsValor.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-varobval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Variáveis, observações e valores
</figcaption>
</figure>
</div>
<p>Uma <strong>variável</strong> é uma característica de interesse medida nas unidades amostrais. Exemplos: peso, altura, sexo, espécie. As variáveis podem ser <strong>numéricas</strong> quando podem ser medidas em escala quantitativa. As variáveis numéricas podem ser divididas em contínuas, quando podem assumir valores reais dentro de uma escala, ou <strong>discretas</strong>, quando só podem assumir números inteiros. Além disso, as variáveis podem ser <strong>categóricas</strong> (ou qualitativas) quando expressam uma classificação de observações em algum agrupamento (por exemplo, sexo ou espécie). As variáveis categóricas podem ser ordinais quando existe uma ordem entre as categorias (por exemplo, ensino fundamental, médio e superior).</p>
<section id="importando-arquivos-excel-de-maneira-fácil" class="level3">
<h3 class="anchored" data-anchor-id="importando-arquivos-excel-de-maneira-fácil">Importando arquivos Excel de maneira fácil</h3>
<p>Vamos importar o conjunto de dados grilos no arquivo Excel <code>dados_R.xlsx</code>, utilizando as instruções abaixo. O conjunto de dados é adaptado de <span class="citation" data-cites="mcdonald2014">McDonald (<a href="#ref-mcdonald2014" role="doc-biblioref">2014</a>)</span> e <span class="citation" data-cites="walker1962">Walker (<a href="#ref-walker1962" role="doc-biblioref">1962</a>)</span>.</p>
<p>A importação de arquivos Excel pode ser realizada em de forma fácil no RStudio seguindo os seguintes passos (<a href="#fig-excel_rstudio" class="quarto-xref">Figura&nbsp;6</a>).</p>
<ol type="1">
<li><p>Acessar aba <code>Environment</code>;</p></li>
<li><p>Clicar no ícone <code>Import Dataset</code>;</p></li>
<li><p>Ir em <code>From Excel</code>;</p></li>
<li><p>Selecionar o arquivo em <code>Browse</code>;</p></li>
<li><p>Selecionar a aba do arquivo (quando ouver mais de uma) no campo <code>Sheet</code>;</p></li>
<li><p>Criar um nome para o objeto em <code>Name</code>;</p></li>
<li><p>Clicar no botão <code>Import</code>.</p></li>
</ol>
<div id="fig-excel_rstudio" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-excel_rstudio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/Fig_read_excel.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-excel_rstudio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Importando arquivos Excel utilizando a interface RStudio. Os passos de 1 a 7 estão ilustrados na figura.
</figcaption>
</figure>
</div>
</section>
<section id="copiando-e-colando-os-dados" class="level3">
<h3 class="anchored" data-anchor-id="copiando-e-colando-os-dados">Copiando e colando os dados</h3>
<p>Conjuntos de dados podem ser importados para o R pelo método “copia e cola” para isso:</p>
<ul>
<li><p>Selecione as linhas e colunas da planilha que deseja copiar;</p></li>
<li><p>No R, execute o seguinte comando para colar os dados da área de transferência como um objeto no R:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.delim2</span>(<span class="st">"clipboard"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co">#em mac:</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.delim2</span>(<span class="fu">pipe</span>(<span class="st">"pbpaste"</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualização-geral-do-conjunto-de-dados" class="level3">
<h3 class="anchored" data-anchor-id="visualização-geral-do-conjunto-de-dados">Visualização geral do conjunto de dados</h3>
<p>Após realizar a importação, é muito importante verificar se não houve problemas na importação. podemos utilizar algumas funções para verificar a estrutura dos dados. Uma função excelente para isso é a função <code>str()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(grilos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [31 × 3] (S3: tbl_df/tbl/data.frame)
 $ Temperatura: num [1:31] 20.8 20.8 24 24 24 24 26.2 26.2 26.2 26.2 ...
 $ Pulsos     : num [1:31] 67.9 65.1 77.3 78.7 79.4 80.4 85.8 86.6 87.5 89.1 ...
 $ Especie    : chr [1:31] "O_exclamationis" "O_exclamationis" "O_exclamationis" "O_exclamationis" ...</code></pre>
</div>
</div>
<p>O objeto <code>grilos</code> foi importado formato tibble. Esta é uma versão versão adaptada dos data frames em R que oferece algumas vantagens em relação aos data frames tradicionais, mas em geral podemos trabalhar com eles da mesma forma que fizemos com data frames no capítulo anterior.</p>
<p>Ao observar o <code>str()</code>, é importante verificarmos por exemplo:</p>
<ul>
<li><p>Se o número de linhas e colunas está correto;</p></li>
<li><p>Se o tipo de variável (caracteres, numéricas) está correto.</p></li>
</ul>
<p>Diversas funções já conhecidas podem nos dar algumas informações sobre o conjunto de dados. Para isso, podemos:</p>
<ol type="1">
<li><p>Digitar o nome do objeto ou utilizar a função <code>View()</code> para visualizá-lo (pelo menos as primeiras linhas);</p></li>
<li><p>utilizar <code>head()</code> ou <code>tail()</code> para visualizar as primeiras linhas e últimas linhas do objeto.</p></li>
<li><p>Utilizar <code>colnames()</code> para verificar os nomes das colunas (variáveis).</p></li>
<li><p>Utilizar <code>ncol()</code>, <code>nrow()</code>, ou <code>dim()</code> para verificar o número de linhas e colunas</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>grilos <span class="co"># visualiza o objeto pinguins no console</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(grilos) <span class="co"># abre o conjunto de dados em uma aba</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(grilos) <span class="co"># ver as primeiras observações</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(grilos)<span class="co"># ver as últimas observações</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(grilos) <span class="co"># ver nomes das colunas</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(grilos) <span class="co"># número de colunas</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(grilos) <span class="co"># número de linhas</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(grilos) <span class="co"># Dimensões do objeto (linhas e colunas)</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Podemos utilizar a função <code>table()</code> para ter informações mais detalhadas sobre variáveis categóricas. Abaixo vamos contar quantas observações (linhas) temos para cada espécie;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(grilos<span class="sc">$</span>Especie)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
O_exclamationis        O_niveus 
             14              17 </code></pre>
</div>
</div>
</section>
</section>
<section id="análise-exploratória" class="level2">
<h2 class="anchored" data-anchor-id="análise-exploratória">Análise exploratória</h2>
<section id="estatísticas-descritivas" class="level3">
<h3 class="anchored" data-anchor-id="estatísticas-descritivas">Estatísticas descritivas</h3>
<p>Vamos calcular estatísticas descritivas para a coluna correspondente à quantidade de pulsos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>grilos<span class="sc">$</span>Pulsos </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Utilizaremos as seguintes funções para calcular as estatísticas descritivas:</p>
<ul>
<li><p><code>mean()</code>: cálculo da média;</p></li>
<li><p><code>median()</code>: cálculo da mediana;</p></li>
<li><p><code>var()</code>: cálculo da variância;</p></li>
<li><p><code>sd()</code>: cálculo do desvio padrão;</p></li>
<li><p><code>summary()</code>: cálculo de diversas estatísticas descritivas.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(grilos<span class="sc">$</span>Pulsos ) <span class="co">#média</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 72.8871</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(grilos<span class="sc">$</span>Pulsos )<span class="co">#mediana</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(grilos<span class="sc">$</span>Pulsos ) <span class="co">#variância</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 286.0725</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(grilos<span class="sc">$</span>Pulsos) <span class="co">#desvio padrão</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.91368</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grilos<span class="sc">$</span>Pulsos) <span class="co">#mínimo, máximo, mediana, média e 1º e 3º quartis</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  44.30   59.45   76.20   72.89   85.25  101.70 </code></pre>
</div>
</div>
</section>
</section>
<section id="cálculo-de-várias-estatísticas-descritivas-por-grupo" class="level2">
<h2 class="anchored" data-anchor-id="cálculo-de-várias-estatísticas-descritivas-por-grupo">Cálculo de várias estatísticas descritivas por grupo</h2>
<p>Como temos medidas para espécies diferentes, podemos comparar as médias de pulsos entre as espécies. Para isso, podemos utilizar a função <code>tapply()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#média por espécie</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(grilos<span class="sc">$</span>Pulsos, grilos<span class="sc">$</span>Especie, mean)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>O_exclamationis        O_niveus 
       85.58571        62.42941 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#desvio padrão por espécie</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(grilos<span class="sc">$</span>Pulsos, grilos<span class="sc">$</span>Especie, sd)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>O_exclamationis        O_niveus 
       11.69930        12.95684 </code></pre>
</div>
</div>
<p>O conjunto de pacotes tidyverse apresenta ferramentas interessantes para análise de conjunto de dados grandes. Para isso é preciso instalar o pacote, clicando em <code>tools:install Packages</code> e procurando pelo pacote ou executando o comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>) <span class="co">#instalar o pacote</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Após instalado o pacote, o tidyverse deve ser carregado com a função <code>library()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#abrir o pacote</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>grilos <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Especie) <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">mean</span>(Pulsos), <span class="at">DP =</span> <span class="fu">sd</span>(Pulsos))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  Especie         media    DP
  &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt;
1 O_exclamationis  85.6  11.7
2 O_niveus         62.4  13.0</code></pre>
</div>
</div>
<p>Este código utilizou o operador “pipe” <code>%&gt;%</code> que permite concatenar uma função após a outra de forma mais clara do que utilizando a notação tradicional. A partir dos dados <code>pinguins</code>, as amostras foram agrupadas pela variável <strong>especie</strong> com a função <code>group_by()</code>, e depois <code>summarise()</code> para calcular estatísticas descritivas.</p>
</section>
<section id="gráficos" class="level2">
<h2 class="anchored" data-anchor-id="gráficos">Gráficos</h2>
<p>O R apresenta ferramentas excelentes para a preparação de gráficos. Diversos pacotes também podem ser usados para aprimorar os gráficos. Neste curso, iremos aprender a fazer gráficos com foco no pacote <code>ggplot2</code> do conjunto de pacotes <code>tidyverse</code>.</p>
<p>As capacidades gráficas do R podem ser expandidas de forma expressiva com a utilização de pacotes. Um O pacote <code>ggplot2</code> permite a preparação de gráficos com qualidade de publicação de maneira fácil. O pacote utiliza uma linguagem diferente da forma tradicional para a elaboração de gráficos no R, conhecida como gramática dos gráficos <span class="citation" data-cites="wilkinson2005">(<a href="#ref-wilkinson2005" role="doc-biblioref">Wilkinson e Wills 2005</a>)</span>. No <code>ggplot2</code>, cada elemento gráfico é adicionado como uma camada.</p>
<p>Em geral, a estrutura do gráfico no <strong>ggplot2</strong> vai seguir uma estrutura geral, na qual vamos adicionando complexidade para os gráficos em diferentes camadas. As camadas podem ser adicionadas utilizando funções:</p>
<ol type="1">
<li><p><strong>Criar novo ggplot</strong>: isso pode ser realizado utilizando a função <code>ggplot()</code>. Nela podemos adicionar como argumentos o conjunto e dados a ser utilizado e também a estética (<em>aesthetics</em>; função <code>aes()</code>).</p></li>
<li><p><strong>Adicionar a estética (<em>aesthetics</em>)</strong>: é adicionada pela função <code>aes()</code>. Os argumentos a serem adicionados variam dependendo do gráfico, mas podm incluir as variáveis a serem plotadas nos eixos (argumentos <code>x =</code> e <code>y =</code>), cores e preenchimentos (<code>col =</code> e <code>fill =</code>), formato de pontos ou tipos de linhas (<code>pch =</code> e <code>linetype =</code>) ou fatores de agrupamento (<code>group =</code>).</p></li>
<li><p><strong>Adicionar geometria (<em>geom</em>)</strong>: a geometria definiria o tipo de gráfico, como gráficos de barras (<code>geom_bar()</code>), histogramas(<code>geom_histogram()</code>) boxplot (<code>geom_boxplot()</code>), gráficos de dispersão (<code>geom_point()</code>)</p></li>
<li><p><strong>Parâmetros adicionais</strong>: outros parâmetros podem ser adicionados. Eles podem alterar características como títulos (<code>ggtitle()</code>), etiquetas dos eixos (<code>xlab()</code> e <code>ylab()</code>), ou temas (funções <code>theme_…()</code>).</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>) <span class="co"># instalar o pacote</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#abrir o pacote</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="gráfico-de-dispersão-scatterplot" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-de-dispersão-scatterplot">Gráfico de dispersão (scatterplot)</h3>
<p>Gráficos de dispersão servem para ver a relação entre duas variáveis contínuas, sendo que uma é poltada no eixo <span class="math inline">\(x\)</span> e a outra no eixo <span class="math inline">\(y\)</span>. no r básico, esse tipo de gráfico pode ser feito com a função <code>plot()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Pulsos <span class="sc">~</span> Temperatura, <span class="at">data =</span> grilos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O ggplot2 permite a confecção de gráficos mais avançados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grilos, <span class="fu">aes</span>(<span class="at">y =</span> Pulsos, <span class="at">x =</span> Temperatura, <span class="at">col =</span> Especie))<span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="boxplots" class="level3">
<h3 class="anchored" data-anchor-id="boxplots">Boxplots</h3>
<p>Boxplots são interessantes para comparar grupos. As caixas representam os valores mínimos e máximos (excluindo valores extremos), os quartis superior e inferior e a mediana. Vamos utilizar um boxplot para comparar os pulsos entre as espécies com a função <code>boxplot()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Pulsos <span class="sc">~</span> Especie, <span class="at">data =</span> grilos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>isso pode ser feito no <strong>ggplot2</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grilos, <span class="fu">aes</span>(<span class="at">y =</span> Pulsos, <span class="at">x =</span> Especie))<span class="sc">+</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="inferência-estatística-utilizando-modelos-lineares" class="level2">
<h2 class="anchored" data-anchor-id="inferência-estatística-utilizando-modelos-lineares">Inferência estatística utilizando modelos lineares</h2>
<section id="teste-t" class="level3">
<h3 class="anchored" data-anchor-id="teste-t">Teste-T</h3>
<p>O teste-t pode ser utilizado para comparar dois grupos. Vamos realizar um teste-t para avaliar se há diferenças entre o número de pulsos entre as espécies de grilos. Nesse caso, temos uma variável de interesse (<strong>variável resposta</strong>) que é o número de pulsos e uma <strong>variável preditora</strong> que é a espécie.</p>
<p>Testamos as seguintes hipóteses:</p>
<ul>
<li><p><strong>Hipótese nula (H₀):</strong>&nbsp;não há diferença na média de pulsos entre as duas espécies.</p></li>
<li><p><strong>Hipótese alternativa (H₁):</strong>&nbsp;existe diferença (pode ser para mais ou para menos).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Pulsos <span class="sc">~</span> Especie, <span class="at">data =</span> grilos)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Pulsos by Especie
t = 5.2236, df = 28.719, p-value = 1.401e-05
alternative hypothesis: true difference in means between group O_exclamationis and group O_niveus is not equal to 0
95 percent confidence interval:
 14.08583 32.22677
sample estimates:
mean in group O_exclamationis        mean in group O_niveus 
                     85.58571                      62.42941 </code></pre>
</div>
</div>
<p>O resultado mostra:</p>
<ul>
<li><p><strong>t = 5.22</strong>&nbsp;→ valor do teste, quanto maior, mais evidência contra H₀.</p></li>
<li><p><strong>p-value = 0.000014</strong>&nbsp;→ extremamente baixo (&lt; 0.05), ou seja, rejeitamos a hipótese nula. Há diferença significativa entre as médias.</p></li>
<li><p><strong>Intervalo de confiança (95%) = [14.09 ; 32.23]</strong>&nbsp;→ a diferença média esperada está entre 14 e 32 pulsos. Como o intervalo não inclui 0, reforça que as médias são de fato diferentes.</p></li>
<li><p><em>Médias: O_exclamationis</em>: média ≈ 85,6 <em>O_niveus</em>: média ≈ 62,4 →&nbsp;<em>O_exclamationis</em>&nbsp;apresenta em média&nbsp;cerca de <strong>23 pulsos a mais</strong>&nbsp;que&nbsp;<em>O_niveus</em>.</p></li>
</ul>
<p>Desta forma dizemos que há diferenças significativas entre as duas espécies. Podemos ilustrar isso com o boxplot que fizemos anteriormente.</p>
</section>
<section id="regressão-linear" class="level3">
<h3 class="anchored" data-anchor-id="regressão-linear">Regressão linear</h3>
<p>A regressão linear permite avaliar a existência de relação entre variáveis contínuas. Nesse caso, temos nossa variável independente (variável resposta) e uma ou mais variáveis preditoras. Para análises de regressão linear podemos ajustar um modelo linear para explicar a quantidade de pulsos em relação à temperatura com a função <code>lm()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>grilos.mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Pulsos <span class="sc">~</span> Temperatura, <span class="at">data =</span> grilos)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>grilos.mod1</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pulsos ~ Temperatura, data = grilos)

Coefficients:
(Intercept)  Temperatura  
    -27.948        4.243  </code></pre>
</div>
</div>
<p>Aqui observamos o intercepto, que representa o valor esperado de&nbsp;<span class="math inline">\(y\)</span>&nbsp;quando&nbsp;<span class="math inline">\(x=0\)</span>, e a inclinação, que indica quanto&nbsp;<span class="math inline">\(y\)</span>&nbsp;se altera a cada unidade adicionada em&nbsp;<span class="math inline">\(x\)</span>.</p>
<p>Podemos verificar o sumário do modelo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grilos.mod1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pulsos ~ Temperatura, data = grilos)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.7044 -2.5789 -0.4466  4.5353  7.5916 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -27.9476     5.5937  -4.996 2.56e-05 ***
Temperatura   4.2431     0.2325  18.251  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.868 on 29 degrees of freedom
Multiple R-squared:  0.9199,    Adjusted R-squared:  0.9171 
F-statistic: 333.1 on 1 and 29 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Esses resultados apresentam as seguintes informações:</p>
<ul>
<li><p><strong>Equação ajustada:</strong> <span class="math inline">\(Pulsos=−27.95+4.24×Temperatura\)</span>.</p></li>
<li><p><strong>Intercepto:</strong>&nbsp;-27,95 → valor esperado de pulsos quando a temperatura é zero (não tem interpretação biológica direta aqui, mas é parte do modelo).</p></li>
<li><p><strong>Inclinação:</strong>&nbsp;4,24 → a cada aumento de&nbsp;<strong>1 °C</strong>, espera-se em média um aumento de&nbsp;<strong>4,2 pulsos</strong>.</p></li>
<li><p><strong>Significância</strong>: Tanto o intercepto (p = 2,56e-05) quanto a inclinação (p &lt; 2e-16) são altamente significativos (***). Isso significa que a temperatura tem efeito estatisticamente forte sobre o número de pulsos.</p></li>
<li><p><strong>R² = 0,92</strong>&nbsp;(ajustado = 0,917) → o modelo explica cerca de&nbsp;<strong>92% da variação</strong>&nbsp;no número de pulsos.</p></li>
</ul>
<p>Podemos observar este resultado no gráfico:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Pulsos <span class="sc">~</span> Temperatura, <span class="at">data =</span> grilos)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(grilos.mod1)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="anova" class="level3">
<h3 class="anchored" data-anchor-id="anova">ANOVA</h3>
<p>A análise de variância é como se fosse uma extensão do teste-t para quando comparamos as médias de mais de dois grupos. Nesse caso temos uma <strong>variável resposta</strong> contínua e uma variável preditora categórica com três níveis ou mais.</p>
<p>Para o exemplo abaixo, vamos importar o conjunto de dados <strong>produtividade</strong>, onde temos 10 observações do rendimento de uma determinada cultura em 3 tipos de solo diferentes: arenoso, argiloso e franco. Os dados foram adaptados de <span class="citation" data-cites="jones2022">Jones, Harden, e Crawley (<a href="#ref-jones2022" role="doc-biblioref">2022</a>)</span></p>
<p><img src="images/clipboard-2105564957.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(prod)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [30 × 2] (S3: tbl_df/tbl/data.frame)
 $ rendimento: num [1:30] 6 10 8 6 14 17 9 11 7 11 ...
 $ solo      : chr [1:30] "arenoso" "arenoso" "arenoso" "arenoso" ...</code></pre>
</div>
</div>
<p>Vamos visualizar um boxplot com os dados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(rendimento <span class="sc">~</span> solo, <span class="at">data =</span> prod)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Parece que a produtividade é menor no solo arenoso, intermediária no solo argiloso e maior no solo franco.</p>
<p>Vamos testar isso criando um modelo de ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>prod.mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(rendimento <span class="sc">~</span> solo, <span class="at">data =</span> prod)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(prod.mod)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: rendimento
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
solo       2   99.2  49.600  4.2447 0.02495 *
Residuals 27  315.5  11.685                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>A análise de variância (ANOVA) indicou que o fator&nbsp;<strong>solo</strong>&nbsp;exerce efeito significativo sobre o rendimento dos grupos analisados (F = 4,24; p = 0,025). Isso significa que os diferentes tipos de solo explicam parte da variação observada na produção, havendo evidências de que pelo menos dois solos apresentam médias distintas de rendimento.</p>
<p>Contudo, a ANOVA não especifica quais grupos diferem entre si, sendo necessário um teste pós-hoc, como o&nbsp;<strong>Tukey HSD</strong>, para identificar as comparações responsáveis por essa diferença.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="fu">aov</span>(prod.mod))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = prod.mod)

$solo
                 diff        lwr      upr     p adj
argiloso-arenoso  1.6 -2.1903777 5.390378 0.5546301
franco-arenoso    4.4  0.6096223 8.190378 0.0204414
franco-argiloso   2.8 -0.9903777 6.590378 0.1785489</code></pre>
</div>
</div>
<p>O teste de comparações múltiplas de Tukey mostrou que, entre os três tipos de solo, apenas a diferença entre&nbsp;<strong>franco e arenoso</strong>&nbsp;foi significativa (diferença média = 4,4; IC95% = 0,61 a 8,19; p = 0,020), indicando maior rendimento no solo franco. As comparações entre&nbsp;<strong>argiloso e arenoso</strong>&nbsp;(diferença = 1,6; p = 0,55) e entre&nbsp;<strong>franco e argiloso</strong>&nbsp;(diferença = 2,8; p = 0,18) não apresentaram diferenças estatisticamente significativas. Assim, o resultado sugere que apenas o solo franco se destacou, produzindo rendimentos superiores ao arenoso.</p>
</section>
<section id="ancova" class="level3">
<h3 class="anchored" data-anchor-id="ancova">ANCOVA</h3>
<p>A ANCOVA é um misto entre a ANOVA e a regressão, onde além da variável <strong>resposta</strong>, temos <strong>preditoras</strong> <strong>contínuas</strong> e <strong>categóricas</strong>. vamos retornar aos dados de grilos, onde além de levarmos em consideração a relação entre pulsos e temperatura, incluímos também a espécie como <strong>covariável</strong>.</p>
<p>Vamos visualizar graficamente esta relação, incluindo uma linha de tendências com o <strong>ggplot2</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(grilos, <span class="fu">aes</span>(<span class="at">y =</span> Pulsos, <span class="at">x =</span> Temperatura, <span class="at">col =</span> Especie))<span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico mostra a relação entre temperatura e número de pulsos em duas espécies de grilos,&nbsp;<em>O_exclamationis</em>&nbsp;(vermelho) e&nbsp;<em>O_niveus</em>&nbsp;(azul). Em ambas, observa-se um aumento linear dos pulsos com o acréscimo de temperatura, indicando uma forte relação positiva entre as variáveis. As inclinações das retas são semelhantes, sugerindo que as duas espécies respondem de forma parecida ao aumento da temperatura; no entanto,&nbsp;<em>O_exclamationis</em>&nbsp;apresenta consistentemente mais pulsos em todas as temperaturas analisadas, evidenciando uma diferença significativa entre as espécies.</p>
<p>Vamos testar isso com um modelo linear (ANCOVA):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>grilos.mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Pulsos <span class="sc">~</span> Temperatura <span class="sc">+</span> Especie, <span class="at">data =</span> grilos)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>grilos.mod2</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pulsos ~ Temperatura + Especie, data = grilos)

Coefficients:
    (Intercept)      Temperatura  EspecieO_niveus  
         -7.211            3.603          -10.065  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grilos.mod2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Pulsos ~ Temperatura + Especie, data = grilos)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0128 -1.1296 -0.3912  0.9650  3.7800 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      -7.21091    2.55094  -2.827  0.00858 ** 
Temperatura       3.60275    0.09729  37.032  &lt; 2e-16 ***
EspecieO_niveus -10.06529    0.73526 -13.689 6.27e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.786 on 28 degrees of freedom
Multiple R-squared:  0.9896,    Adjusted R-squared:  0.9888 
F-statistic:  1331 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>O modelo de regressão linear múltipla mostrou que tanto a&nbsp;<strong>temperatura</strong>&nbsp;quanto a&nbsp;<strong>espécie</strong>&nbsp;influenciam significativamente o número de pulsos. A cada aumento de 1 °C, ocorre um acréscimo médio de aproximadamente&nbsp;<strong>3,6 pulsos</strong>. Além disso, a espécie&nbsp;<em>O_niveus</em>&nbsp;apresenta, em média, cerca de&nbsp;<strong>10 pulsos a menos</strong>&nbsp;que&nbsp;<em>O_exclamationis</em>, mantendo constante o efeito da temperatura. O modelo apresenta excelente qualidade de ajuste (<strong>R² = 0,99</strong>), explicando quase toda a variação observada nos dados, com resíduos pequenos e distribuídos de forma adequada, confirmando que temperatura e espécie são fortes preditores do número de pulsos</p>
</section>
<section id="avaliando-os-pressupostos-de-um-modelo" class="level3">
<h3 class="anchored" data-anchor-id="avaliando-os-pressupostos-de-um-modelo">Avaliando os pressupostos de um modelo</h3>
<p>Os modelos lineares apresentam pressupostos que precisam ser verificados para garantir a validade dos resultados. Dois deles são fundamentais: a&nbsp;<strong>normalidade dos resíduos</strong>&nbsp;e a&nbsp;<strong>homoscedasticidade</strong>. A normalidade dos resíduos significa que os erros (diferença entre valores observados e preditos) devem se distribuir aproximadamente de forma normal, o que assegura que as estimativas de significância sejam confiáveis. Já a homoscedasticidade refere-se à constância da variância dos resíduos ao longo de todos os valores preditos, ou seja, a dispersão dos erros deve ser semelhante em diferentes níveis da variável explicativa. Quando esses pressupostos são atendidos, o modelo linear oferece estimativas mais robustas e interpretações estatisticamente válidas.</p>
<p>Podemos conferir esses pressupostos no R utilizando a função <code>plot()</code> para o modelo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grilos.mod2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Os gráficos apresentam as seguintes informações:</p>
<ul>
<li><p><strong>Residuals vs Fitted</strong>&nbsp;→ mostra se há relação sistemática entre resíduos e valores ajustados. Deve aparecer uma nuvem aleatória de pontos; padrões em curva ou funil sugerem problemas de linearidade ou heterocedasticidade.</p></li>
<li><p><strong>Normal Q-Q</strong>&nbsp;→ verifica se os resíduos seguem distribuição normal. Os pontos devem se alinhar próximos à linha reta; desvios grandes nas extremidades indicam caudas não normais.</p></li>
<li><p><strong>Scale-Location (Spread-Location)</strong>&nbsp;→ avalia homoscedasticidade, isto é, variância constante dos resíduos. A dispersão deve ser uniforme ao longo dos valores ajustados; se há funil ou tendência, indica heterocedasticidade.</p></li>
<li><p><strong>Residuals vs Leverage</strong>&nbsp;→ identifica observações influentes. Pontos com alto&nbsp;<em>leverage</em>&nbsp;(alavancagem) e grande distância de Cook podem afetar fortemente o ajuste do modelo e merecem atenção.</p></li>
</ul>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referências</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-jones2022" class="csl-entry" role="listitem">
Jones, Elinor, Simon Harden, e Michael J. Crawley. 2022. <em>The R book</em>. Third edition. Hoboken, NJ: Wiley.
</div>
<div id="ref-mcdonald2014" class="csl-entry" role="listitem">
McDonald. 2014. <em>Handbook of Biological Statistics</em>. Third.
</div>
<div id="ref-walker1962" class="csl-entry" role="listitem">
Walker, Thomas J. 1962. <span>“The Taxonomy and Calling Songs of United States Tree Crickets (Orthoptera: Gryllidae: Oecanthinae). I. The Genus Neoxabea and the Niveus and Varicornis Groups of the Genus Oecanthus1”</span>. <em>Annals of the Entomological Society of America</em> 55 (3): 303–22. <a href="https://doi.org/10.1093/aesa/55.3.303">https://doi.org/10.1093/aesa/55.3.303</a>.
</div>
<div id="ref-wickham2023" class="csl-entry" role="listitem">
Wickham, Hadley, Mine Çetinkaya-Rundel, e Garrett Grolemund. 2023. <em>R for data science: import, tidy, transform, visualize, and model data</em>. 2nd edition. Sebastopol, CA: O’Reilly Media, Inc.
</div>
<div id="ref-wilkinson2005" class="csl-entry" role="listitem">
Wilkinson, Leland, e Graham Wills. 2005. <em>The Grammar of Graphics</em>. 2nd ed. Statistics e Computing. New York: Springer.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>